#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Refresh the auto-generated "Other repos" section in README.md.

.DESCRIPTION
    Lists public, non-fork, non-archived repos for the configured user via the
    gh CLI, filters out repos that are already curated above (matched as
    markdown links to repo roots), filters out repos that are special-cased
    elsewhere, and filters out repos with no description or no push in the
    last 12 months. Renders a markdown table between the
    `<!-- repos:more:start -->` and `<!-- repos:more:end -->` markers.

    Writes the file only if content changed. Exits 0 on success regardless of
    whether anything changed; non-zero on hard errors (gh failure, missing
    markers, malformed JSON).

.NOTES
    Requires: gh CLI authenticated, pwsh 7+.
    Designed to run identically locally and in GitHub Actions.
#>
[CmdletBinding()]
param(
    [string]$ReadmePath = (Join-Path (Split-Path $PSScriptRoot -Parent) 'README.md'),
    [string]$User = 'martinopedal',
    [string]$StartMarker = '<!-- repos:more:start -->',
    [string]$EndMarker = '<!-- repos:more:end -->',
    [int]$StaleAfterDays = 365
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Repos that are referenced specially in the README and must never appear in
# the auto-generated table. Compared case-insensitively as nameWithOwner.
$skipFullNames = @(
    "$User/$User",          # the profile repo itself
    "$User/opedal.tech"     # personal site, linked in prose
) | ForEach-Object { $_.ToLowerInvariant() }

if (-not (Test-Path $ReadmePath)) {
    throw "README.md not found at $ReadmePath"
}

# Validate markers: exactly one of each, in the right order.
$readme = Get-Content -Raw -Path $ReadmePath
$startCount = ([regex]::Matches($readme, [regex]::Escape($StartMarker))).Count
$endCount = ([regex]::Matches($readme, [regex]::Escape($EndMarker))).Count
if ($startCount -ne 1 -or $endCount -ne 1) {
    throw "Expected exactly one '$StartMarker' and one '$EndMarker' in README.md (found $startCount start, $endCount end)."
}
$startIdx = $readme.IndexOf($StartMarker)
$endIdx = $readme.IndexOf($EndMarker)
if ($endIdx -lt $startIdx) {
    throw "End marker appears before start marker in README.md."
}

$before = $readme.Substring(0, $startIdx)
$after = $readme.Substring($endIdx + $EndMarker.Length)

# Curated repos are markdown links to repo roots. This deliberately ignores
# issue links, blob links, compare links, or anything beyond the repo root,
# so a deep link to a sub-page does not silently mark a repo as curated.
$curatedFullNames = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)
$linkPattern = [regex]("\]\(https://github\.com/" + [regex]::Escape($User) + "/([A-Za-z0-9_.\-]+)/?\)")
foreach ($m in $linkPattern.Matches($before + $after)) {
    [void]$curatedFullNames.Add("$User/$($m.Groups[1].Value)")
}

Write-Host "Fetching public, non-archived repos for $User..."
$ghArgs = @(
    'repo','list',$User,
    '--limit','200',
    '--no-archived',
    '--visibility','public',
    '--json','name,nameWithOwner,description,primaryLanguage,pushedAt,url,isFork,stargazerCount'
)
$ghJson = & gh @ghArgs
if ($LASTEXITCODE -ne 0) {
    throw "gh repo list failed with exit code $LASTEXITCODE"
}

$repos = @()
try {
    $repos = $ghJson | ConvertFrom-Json
} catch {
    throw "Failed to parse gh JSON output: $_"
}

if ($null -eq $repos) { $repos = @() }

$staleCutoff = (Get-Date).ToUniversalTime().AddDays(-$StaleAfterDays)

$candidates = @($repos |
    Where-Object { -not $_.isFork } |
    Where-Object { $skipFullNames -notcontains $_.nameWithOwner.ToLowerInvariant() } |
    Where-Object { -not $curatedFullNames.Contains($_.nameWithOwner) } |
    Where-Object {
        # Skip repos with no description; they dilute the signal.
        -not [string]::IsNullOrWhiteSpace($_.description)
    } |
    Where-Object {
        # Skip stale repos.
        if (-not $_.pushedAt) { return $false }
        try {
            ([DateTime]$_.pushedAt).ToUniversalTime() -ge $staleCutoff
        } catch {
            $false
        }
    } |
    Sort-Object { [DateTime]$_.pushedAt } -Descending)

$rows = @(foreach ($r in $candidates) {
    $desc = $r.description.Trim()
    # Markdown table cells: escape pipes, collapse newlines, strip backticks
    # to avoid breaking inline code formatting that the description never
    # opened.
    $desc = $desc -replace '\r?\n', ' ' -replace '\|', '\|'
    $lang = if ($r.primaryLanguage -and $r.primaryLanguage.name) { $r.primaryLanguage.name } else { 'Unknown' }
    $stars = [int]$r.stargazerCount
    $pushed = ([DateTime]$r.pushedAt).ToUniversalTime().ToString('yyyy-MM-dd')
    "| [$($r.name)]($($r.url)) | $desc | $lang | $stars | $pushed |"
})

$bodyLines = if ($rows.Count -gt 0) {
    @(
        '<!-- generated by scripts/update-readme.ps1, do not edit by hand -->'
        ''
        '| Repo | Description | Language | Stars | Last push |'
        '|------|-------------|----------|-------|-----------|'
    ) + $rows
} else {
    @(
        '<!-- generated by scripts/update-readme.ps1, do not edit by hand -->'
        ''
        '_No additional public repos to surface right now. Every active repo with a description is curated above._'
    )
}
$body = $bodyLines -join "`n"

$generated = "$StartMarker`n$body`n$EndMarker"
$updated = $before + $generated + $after

if ($updated -ne $readme) {
    # Preserve the original line ending convention. README.md is committed
    # with LF; Set-Content with -NoNewline keeps the existing trailing state.
    $bytes = [System.Text.UTF8Encoding]::new($false).GetBytes($updated)
    [System.IO.File]::WriteAllBytes($ReadmePath, $bytes)
    Write-Host "README.md updated. $($candidates.Count) repo(s) in auto section."
} else {
    Write-Host "README.md already up to date."
}
